baseURL: https://karanthaker.io/
languageCode: en-us
title: Karan Thaker
theme: PaperMod

enableRobotsTXT: true
# googleAnalytics: todo

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  description: "Personal blog and portfolio"
  keywords: [Blog, Portfolio, Resume, Karan, Thaker]
  author: Karan Thaker
  copyright: "**[Karan Thaker](https://karanthaker.io)**"
  defaultTheme: auto

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  

  profileMode:
    enabled: true
    title: Hi, I'm Karan 👋🏽
    subtitle: like 'current' without the 't'
    imageUrl: "/pkthaker-high-res-current-photo.jpeg"
    imageTitle: "Profile picture of Karan Thaker"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Archive
        url: "/archive"
      - name: Posts
        url: "/posts"
      - name: Tags
        url: "/tags"
      - name: Resume
        url: "/resume"
  
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/p-karanthaker/"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/pkthaker/"
    - name: "Instagram"
      url: "http://www.instagram.com/karanthaker_/"